// Café layout — scale 1.5× (characters and pieces are 1.5× the pool size).
// Background: /maps/cafe_empty.webp (1024×576). Generated by me from measured positions;
// edit freely. Every element is placed by its BOTTOM-CENTRE (x, y), same as characters.
// Move a piece = change its x/y; its collider, seat and interaction move with it.

import type { ElementDef } from '../types';

/** Characters in this room are drawn with the 1.5× frame sets. */
export const CAFE_ACTOR_SCALE = 1.5;

const E = (name: string) => `/sprites/elements/cafe/${name}.webp`;

export const cafeElements: ElementDef[] = [
  { id: 'notice_board', asset: E('notice_board'), x: 560, y: 165, layer: 'wall', interact: { id: 'notice_board', label: 'Read', dx: 0, dy: 125, radius: 70 } },
  { id: 'cushion_blue_1', asset: E('cushion_blue'), x: 116, y: 423, layer: 'floor', seat: { dx: 0, dy: -6, facing: 1 } },
  { id: 'cushion_red_1', asset: E('cushion_red'), x: 308, y: 423, layer: 'floor', seat: { dx: 0, dy: -6, facing: -1 } },
  { id: 'cushion_blue_2', asset: E('cushion_blue'), x: 416, y: 423, layer: 'floor', seat: { dx: 0, dy: -6, facing: 1 } },
  { id: 'cushion_red_2', asset: E('cushion_red'), x: 608, y: 423, layer: 'floor', seat: { dx: 0, dy: -6, facing: -1 } },
  { id: 'cushion_blue_3', asset: E('cushion_blue'), x: 716, y: 423, layer: 'floor', seat: { dx: 0, dy: -6, facing: 1 } },
  { id: 'cushion_red_3', asset: E('cushion_red'), x: 908, y: 423, layer: 'floor', seat: { dx: 0, dy: -6, facing: -1 } },
  { id: 'counter', asset: E('counter'), x: 92, y: 345, layer: 'object', collider: { w: 158, h: 80 } },
  { id: 'bar', asset: E('bar_plain'), x: 228, y: 345, layer: 'object', collider: { w: 101, h: 80 } },
  { id: 'table_1', asset: E('table_coffee'), x: 212, y: 420, layer: 'object', collider: { w: 98, h: 22 } },
  { id: 'table_2', asset: E('table_tea'), x: 512, y: 420, layer: 'object', collider: { w: 98, h: 22 } },
  { id: 'table_3', asset: E('table_coffee'), x: 812, y: 420, layer: 'object', collider: { w: 98, h: 22 } },
  { id: 'bookshelf', asset: E('bookshelf'), x: 470, y: 270, layer: 'object', collider: { w: 100, h: 12 }, interact: { id: 'bookshelf', label: 'Browse', dx: 0, dy: 25, radius: 60 } },
  { id: 'menu_board', asset: E('menu_board'), x: 578, y: 272, layer: 'object', collider: { w: 70, h: 10 }, interact: { id: 'menu_board', label: 'Menu', dx: 0, dy: 22, radius: 55 } },
  { id: 'plant_small', asset: E('plant_small'), x: 922, y: 268, layer: 'object', collider: { w: 50, h: 10 } },
  { id: 'monstera_left', asset: E('monstera'), x: 40, y: 576, layer: 'object', collider: { w: 90, h: 26 } },
  { id: 'monstera_right', asset: E('monstera'), x: 984, y: 576, layer: 'object', collider: { w: 90, h: 26 } },];

/** Barista stands behind the plain bar; the bar hides the legs (bar y is larger, so it's drawn later). */
export const BARISTA_SPOT = { x: 228, y: 318, facing: 1 as const };

/** Pinned-note positions on the notice board (note.webp) for today's tip. */
export const NOTE_SPOTS = [{ x: 540, y: 138 }, { x: 580, y: 146 }];

/** Spare pieces (not placed): rug, coffee_bar (with tools), chemex, kettle, stool, books, cup. */
